version: '3.8'

services:
  backend:
    image: anujgope/claimshield-backend:latest
    container_name: claimshield-backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=production
      # Pulling variables from the host environment
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - AWS_REGION=${AWS_REGION:-eu-north-1}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    image: anujgope/claimshield-frontend:latest
    container_name: claimshield-frontend
    ports:
      - "80:80"
      - "5173:5173" # Keep Vite default port open for dev familiarity if needed
    depends_on:
      - backend
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
